Akatsuki_ThiGiuaKy/Akatsuki_ThiGiuaKy/Entities/DatVe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Akatsuki_ThiGiuaKy.Entities
{
    public class DatVe
    {
        [Key]
        public int MaDatVe { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Số điện thoại người xem")]
        public string SoDienThoai { get; set; }

        [ForeignKey(nameof(LichChieuPhim))]
        [Display(Name = "Lịch chiếu")]
        public int MaLichChieuPhim { get; set; }

        [Range(1, Int32.MaxValue)]
        [Display(Name = "Số lượng đặt")]
        public int SoLuong { get; set; } = 1;

        public LichChieuPhim LichChieuPhim { get; set; }

        [Display(Name = "Vé được đặt lúc")]
        public DateTime ThoiGianDat { get; set; }
    }
}

Akatsuki_ThiGiuaKy/Akatsuki_ThiGiuaKy/Controllers/DatVesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Akatsuki_ThiGiuaKy.Entities;

namespace Akatsuki_ThiGiuaKy.Controllers
{
    public class DatVesController : Controller
    {
        private readonly MyDbContext _context;

        public DatVesController(MyDbContext context)
        {
            _context = context;
        }

        // GET: DatVes
        public async Task<IActionResult> Index(string searchString)
        {
            //var searchDS = (from c in _context.DatVes
            //                    select c).ToList();
            //if (!string.IsNullOrEmpty(searchString))
            //{
            //    searchDS = searchDS.Where(s => s.MaLichChieuPhim.Contains(searchString)).ToList();
            //}
            var myDbContext = _context.DatVes.Include(d => d.LichChieuPhim);
            return View(await myDbContext.ToListAsync());           
        }

        // GET: DatVes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datVe = await _context.DatVes
                .Include(d => d.LichChieuPhim)
                .FirstOrDefaultAsync(m => m.MaDatVe == id);
            if (datVe == null)
            {
                return NotFound();
            }

            return View(datVe);
        }

        // GET: DatVes/Create
        public IActionResult Create()
        {
            ViewData["MaLichChieuPhim"] = new SelectList(_context.LichChieuPhims, "MaLichChieuPhim", "MaLichChieuPhim");
            return View();
        }

        // POST: DatVes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaDatVe,SoDienThoai,MaLichChieuPhim,SoLuong,ThoiGianDat")] DatVe datVe)
        {
            if (ModelState.IsValid)
            {
                _context.Add(datVe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLichChieuPhim"] = new SelectList(_context.LichChieuPhims, "MaLichChieuPhim", "MaLichChieuPhim", datVe.MaLichChieuPhim);
            return View(datVe);
        }

        // GET: DatVes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datVe = await _context.DatVes.FindAsync(id);
            if (datVe == null)
            {
                return NotFound();
            }
            ViewData["MaLichChieuPhim"] = new SelectList(_context.LichChieuPhims, "MaLichChieuPhim", "MaLichChieuPhim", datVe.MaLichChieuPhim);
            return View(datVe);
        }

        // POST: DatVes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaDatVe,SoDienThoai,MaLichChieuPhim,SoLuong,ThoiGianDat")] DatVe datVe)
        {
            if (id != datVe.MaDatVe)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(datVe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DatVeExists(datVe.MaDatVe))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLichChieuPhim"] = new SelectList(_context.LichChieuPhims, "MaLichChieuPhim", "MaLichChieuPhim", datVe.MaLichChieuPhim);
            return View(datVe);
        }

        // GET: DatVes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datVe = await _context.DatVes
                .Include(d => d.LichChieuPhim)
                .FirstOrDefaultAsync(m => m.MaDatVe == id);
            if (datVe == null)
            {
                return NotFound();
            }

            return View(datVe);
        }

        // POST: DatVes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var datVe = await _context.DatVes.FindAsync(id);
            _context.DatVes.Remove(datVe);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DatVeExists(int id)
        {
            return _context.DatVes.Any(e => e.MaDatVe == id);
        }             
    }
}

Akatsuki_ThiGiuaKy/Akatsuki_ThiGiuaKy/Views/DatVes/Create.cshtml
@model Akatsuki_ThiGiuaKy.Entities.DatVe

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>DatVe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaLichChieuPhim" class="control-label"></label>
                <select asp-for="MaLichChieuPhim" class ="form-control" asp-items="ViewBag.MaLichChieuPhim"></select>
            </div>
            <div class="form-group">
                <label asp-for="SoLuong" class="control-label"></label>
                <input asp-for="SoLuong" class="form-control" />
                <span asp-validation-for="SoLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThoiGianDat" class="control-label"></label>
                <input asp-for="ThoiGianDat" class="form-control" />
                <span asp-validation-for="ThoiGianDat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Akatsuki_ThiGiuaKy/Akatsuki_ThiGiuaKy/Views/DatVes/DatVe.cshtml
@model Akatsuki_ThiGiuaKy.Entities.DatVe

@{
    ViewData["Title"] = "Đặt vé";
}

<h5 class="mb-3">Đặt vé xem phim</h5>

@if (ViewBag.Message != null)
{
    <div class="alert alert-info" role="alert">
        @ViewBag.Message
    </div>
}

<form asp-controller="Home" asp-action="DatVe">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="SoDienThoai" class="control-label"></label>
        <input asp-for="SoDienThoai" class="form-control" />
        <span asp-validation-for="SoDienThoai" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="MaLichChieuPhim" class="control-label"></label>
        <select asp-for="MaLichChieuPhim" class="form-control" asp-items="ViewBag.LichChieu"></select>
    </div>
    <div class="form-group">
        <label asp-for="SoLuong" class="control-label"></label>
        <input asp-for="SoLuong" class="form-control" />
        <span asp-validation-for="SoLuong" class="text-danger"></span>
    </div>
    <div class="text-left">
        <button type="submit" class="btn btn-primary">Đặt vé</button>
    </div>
</form>

Akatsuki_ThiGiuaKy/Akatsuki_ThiGiuaKy/Views/DatVes/Delete.cshtml
@model Akatsuki_ThiGiuaKy.Entities.DatVe

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DatVe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoDienThoai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoDienThoai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoLuong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LichChieuPhim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LichChieuPhim.MaLichChieuPhim)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ThoiGianDat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ThoiGianDat)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaDatVe" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Akatsuki_ThiGiuaKy/Akatsuki_ThiGiuaKy/Views/DatVes/Details.cshtml
@model Akatsuki_ThiGiuaKy.Entities.DatVe

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DatVe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoDienThoai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoDienThoai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoLuong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LichChieuPhim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LichChieuPhim.MaLichChieuPhim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ThoiGianDat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ThoiGianDat)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MaDatVe">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Akatsuki_ThiGiuaKy/Akatsuki_ThiGiuaKy/Views/DatVes/Edit.cshtml
@model Akatsuki_ThiGiuaKy.Entities.DatVe

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DatVe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaDatVe" />
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaLichChieuPhim" class="control-label"></label>
                <select asp-for="MaLichChieuPhim" class="form-control" asp-items="ViewBag.MaLichChieuPhim"></select>
                <span asp-validation-for="MaLichChieuPhim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuong" class="control-label"></label>
                <input asp-for="SoLuong" class="form-control" />
                <span asp-validation-for="SoLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThoiGianDat" class="control-label"></label>
                <input asp-for="ThoiGianDat" class="form-control" />
                <span asp-validation-for="ThoiGianDat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Akatsuki_ThiGiuaKy/Akatsuki_ThiGiuaKy/Views/DatVes/Index.cshtml
@model IEnumerable<Akatsuki_ThiGiuaKy.Entities.DatVe>

@{
    ViewData["Title"] = "Index";
}

<h1>Danh sách đặt vé</h1>

<div class="btn-group">

    <a href="@Url.Action("DatVe", "Home")">
        <button type="button" class="btn btn-default">
            Create New
        </button>
    </a>
</div>
@using (Html.BeginForm("Index", "DatVes", FormMethod.Get))
{
    <input type="text" name="searchString" />
    <button type="submit">Find</button>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SoDienThoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoLuong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LichChieuPhim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ThoiGianDat)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SoDienThoai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoLuong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LichChieuPhim.MaLichChieuPhim)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ThoiGianDat)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.MaDatVe">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.MaDatVe">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.MaDatVe">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>